// generated by gong
import { Component, OnInit, Inject, Optional } from '@angular/core';
import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop';

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

import { Router, RouterState } from '@angular/router';
import { WasherDB } from '../washer-db'
import { WasherService } from '../washer.service'

import { FrontRepoService, FrontRepo, NullInt64 } from '../front-repo.service'
@Component({
  selector: 'lib-washer-sorting',
  templateUrl: './washer-sorting.component.html',
  styleUrls: ['./washer-sorting.component.css']
})
export class WasherSortingComponent implements OnInit {

  frontRepo: FrontRepo

  // array of Washer instances that are in the association
  associatedWashers = new Array<WasherDB>();

  constructor(
    private washerService: WasherService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of washer instances
    public dialogRef: MatDialogRef<WasherSortingComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };
  }

  ngOnInit(): void {
    this.getWashers()
  }

  getWashers(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        let index = 0
        for (let washer of this.frontRepo.Washers_array) {
          let ID = this.dialogData.ID
          let revPointerID = washer[this.dialogData.ReversePointer]
          let revPointerID_Index = washer[this.dialogData.ReversePointer+"_Index"]
          if (revPointerID.Int64 == ID) {
            if (revPointerID_Index == undefined) {
              revPointerID_Index = new NullInt64
              revPointerID_Index.Valid = true
              revPointerID_Index.Int64 = index++
            }
            this.associatedWashers.push(washer)
          }
        }

        // sort associated washer according to order
        this.associatedWashers.sort((t1, t2) => {
          let t1_revPointerID_Index = t1[this.dialogData.ReversePointer+"_Index"]
          let t2_revPointerID_Index = t2[this.dialogData.ReversePointer+"_Index"]
          if (t1_revPointerID_Index && t2_revPointerID_Index) {
            if (t1_revPointerID_Index.Int64 > t2_revPointerID_Index.Int64) {
              return 1;
            }
            if (t1_revPointerID_Index.Int64 < t2_revPointerID_Index.Int64) {
              return -1;
            }  
          }
          return 0;
        });
      }
    )
  }

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.associatedWashers, event.previousIndex, event.currentIndex);

    // set the order of Washer instances
    let index = 0
    
    for (let washer of this.associatedWashers) {
      let revPointerID_Index = washer[this.dialogData.ReversePointer+"_Index"]
      revPointerID_Index.Valid = true
      revPointerID_Index.Int64 = index++
    }
  }

  save() {

    this.associatedWashers.forEach(
      washer => {
        this.washerService.updateWasher(washer)
          .subscribe(washer => {
            this.washerService.WasherServiceChanged.next("update")
          });
      }
    )

    this.dialogRef.close('Sorting of '+ this.dialogData.ReversePointer+' done');
  }
}
