// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { WasherDB } from '../washer-db'
import { WasherService } from '../washer.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'

// generated table component
@Component({
  selector: 'app-washerstable',
  templateUrl: './washers-table.component.html',
  styleUrls: ['./washers-table.component.css'],
})
export class WashersTableComponent implements OnInit {

  // used if the component is called as a selection component of Washer instances
  selection: SelectionModel<WasherDB>;
  initialSelection = new Array<WasherDB>();

  // the data source for the table
  washers: WasherDB[];
  matTableDataSource: MatTableDataSource<WasherDB>


  // front repo, that will be referenced by this.washers
  frontRepo: FrontRepo

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort) sort: MatSort;
  @ViewChild(MatPaginator) paginator: MatPaginator;

  ngAfterViewInit() {

	// enable sorting on all fields (including pointers and reverse pointer)
	this.matTableDataSource.sortingDataAccessor = (washerDB: WasherDB, property: string) => {
		switch (property) {
				// insertion point for specific sorting accessor
			case 'TechName':
				return washerDB.TechName;

			case 'Name':
				return washerDB.Name;

			case 'DirtyLaundryWeight':
				return washerDB.DirtyLaundryWeight;

			case 'State':
				return washerDB.State;

			case 'Machine':
				return (washerDB.Machine ? washerDB.Machine.Name : '');

			case 'CleanedLaundryWeight':
				return washerDB.CleanedLaundryWeight;

				default:
					return WasherDB[property];
		}
	}; 

	// enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
	this.matTableDataSource.filterPredicate = (washerDB: WasherDB, filter: string) => {

		// filtering is based on finding a lower case filter into a concatenated string
		// the washerDB properties
		let mergedContent = ""

		// insertion point for merging of fields
		mergedContent += washerDB.TechName.toLowerCase()
		mergedContent += washerDB.Name.toLowerCase()
		mergedContent += washerDB.DirtyLaundryWeight.toString()
		mergedContent += washerDB.State.toLowerCase()
		if (washerDB.Machine) {
    		mergedContent += washerDB.Machine.Name.toLowerCase()
		}
		mergedContent += washerDB.CleanedLaundryWeight.toString()

		let isSelected = mergedContent.includes(filter.toLowerCase())
		return isSelected
	};

    this.matTableDataSource.sort = this.sort;
    this.matTableDataSource.paginator = this.paginator;
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private washerService: WasherService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of washer instances
    public dialogRef: MatDialogRef<WashersTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    // observable for changes in structs
    this.washerService.WasherServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getWashers()
        }
      }
    )
    if (dialogData == undefined) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "TechName",
        "Name",
        "DirtyLaundryWeight",
        "State",
        "Machine",
        "CleanedLaundryWeight",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "TechName",
        "Name",
        "DirtyLaundryWeight",
        "State",
        "Machine",
        "CleanedLaundryWeight",
      ]
      this.selection = new SelectionModel<WasherDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getWashers()
    this.matTableDataSource = new MatTableDataSource(this.washers)
  }

  getWashers(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.washers = this.frontRepo.Washers_array;

        // insertion point for variables Recoveries

        // in case the component is called as a selection component
        if (this.dialogData != undefined) {
          this.washers.forEach(
            washer => {
              let ID = this.dialogData.ID
              let revPointer = washer[this.dialogData.ReversePointer]
              if (revPointer.Int64 == ID) {
                this.initialSelection.push(washer)
              }
            }
          )
          this.selection = new SelectionModel<WasherDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.washers
      }
    )
  }

  // newWasher initiate a new washer
  // create a new Washer objet
  newWasher() {
  }

  deleteWasher(washerID: number, washer: WasherDB) {
    // list of washers is truncated of washer before the delete
    this.washers = this.washers.filter(h => h !== washer);

    this.washerService.deleteWasher(washerID).subscribe(
      washer => {
        this.washerService.WasherServiceChanged.next("delete")
      }
    );
  }

  editWasher(washerID: number, washer: WasherDB) {

  }

  // display washer in router
  displayWasherInRouter(washerID: number) {
    this.router.navigate(["github_com_fullstack_lang_laundromat_go-" + "washer-display", washerID])
  }

  // set editor outlet
  setEditorRouterOutlet(washerID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_laundromat_go_editor: ["github_com_fullstack_lang_laundromat_go-" + "washer-detail", washerID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(washerID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_laundromat_go_presentation: ["github_com_fullstack_lang_laundromat_go-" + "washer-presentation", washerID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.washers.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.washers.forEach(row => this.selection.select(row));
  }

  save() {

    let toUpdate = new Set<WasherDB>()

    // reset all initial selection of washer that belong to washer through Anarrayofb
    this.initialSelection.forEach(
      washer => {
        washer[this.dialogData.ReversePointer].Int64 = 0
        washer[this.dialogData.ReversePointer].Valid = true
        toUpdate.add(washer)
      }
    )

    // from selection, set washer that belong to washer through Anarrayofb
    this.selection.selected.forEach(
      washer => {
        let ID = +this.dialogData.ID
        washer[this.dialogData.ReversePointer].Int64 = ID
        washer[this.dialogData.ReversePointer].Valid = true
        toUpdate.add(washer)
      }
    )

    // update all washer (only update selection & initial selection)
    toUpdate.forEach(
      washer => {
        this.washerService.updateWasher(washer)
          .subscribe(washer => {
            this.washerService.WasherServiceChanged.next("update")
          });
      }
    )
    this.dialogRef.close('Pizza!');
  }
}
