// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, NullInt64, SelectionMode } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { WasherDB } from '../washer-db'
import { WasherService } from '../washer.service'

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-washerstable',
  templateUrl: './washers-table.component.html',
  styleUrls: ['./washers-table.component.css'],
})
export class WashersTableComponent implements OnInit {

  // mode at invocation
  mode: TableComponentMode

  // used if the component is called as a selection component of Washer instances
  selection: SelectionModel<WasherDB>;
  initialSelection = new Array<WasherDB>();

  // the data source for the table
  washers: WasherDB[];
  matTableDataSource: MatTableDataSource<WasherDB>

  // front repo, that will be referenced by this.washers
  frontRepo: FrontRepo

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort) sort: MatSort;
  @ViewChild(MatPaginator) paginator: MatPaginator;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (washerDB: WasherDB, property: string) => {
      switch (property) {
        // insertion point for specific sorting accessor
        case 'TechName':
          return washerDB.TechName;

        case 'Name':
          return washerDB.Name;

        case 'DirtyLaundryWeight':
          return washerDB.DirtyLaundryWeight;

        case 'State':
          return washerDB.State;

        case 'Machine':
          return (washerDB.Machine ? washerDB.Machine.Name : '');

        case 'CleanedLaundryWeight':
          return washerDB.CleanedLaundryWeight;

        default:
          return WasherDB[property];
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (washerDB: WasherDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the washerDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += washerDB.TechName.toLowerCase()
      mergedContent += washerDB.Name.toLowerCase()
      mergedContent += washerDB.DirtyLaundryWeight.toString()
      mergedContent += washerDB.State.toLowerCase()
      if (washerDB.Machine) {
        mergedContent += washerDB.Machine.Name.toLowerCase()
      }
      mergedContent += washerDB.CleanedLaundryWeight.toString()

      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort;
    this.matTableDataSource.paginator = this.paginator;
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private washerService: WasherService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of washer instances
    public dialogRef: MatDialogRef<WashersTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.washerService.WasherServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getWashers()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "TechName",
        "Name",
        "DirtyLaundryWeight",
        "State",
        "Machine",
        "CleanedLaundryWeight",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "TechName",
        "Name",
        "DirtyLaundryWeight",
        "State",
        "Machine",
        "CleanedLaundryWeight",
      ]
      this.selection = new SelectionModel<WasherDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getWashers()
    this.matTableDataSource = new MatTableDataSource(this.washers)
  }

  getWashers(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.washers = this.frontRepo.Washers_array;

        // insertion point for variables Recoveries

        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          this.washers.forEach(
            washer => {
              let ID = this.dialogData.ID
              let revPointer = washer[this.dialogData.ReversePointer]
              if (revPointer.Int64 == ID) {
                this.initialSelection.push(washer)
              }
            }
          )
          this.selection = new SelectionModel<WasherDB>(allowMultiSelect, this.initialSelection);
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s"]
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)

          if (sourceInstance[this.dialogData.SourceField]) {
            for (let associationInstance of sourceInstance[this.dialogData.SourceField]) {
              let washer = associationInstance[this.dialogData.IntermediateStructField]
              this.initialSelection.push(washer)
            }
          }
          this.selection = new SelectionModel<WasherDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.washers
      }
    )
  }

  // newWasher initiate a new washer
  // create a new Washer objet
  newWasher() {
  }

  deleteWasher(washerID: number, washer: WasherDB) {
    // list of washers is truncated of washer before the delete
    this.washers = this.washers.filter(h => h !== washer);

    this.washerService.deleteWasher(washerID).subscribe(
      washer => {
        this.washerService.WasherServiceChanged.next("delete")
      }
    );
  }

  editWasher(washerID: number, washer: WasherDB) {

  }

  // display washer in router
  displayWasherInRouter(washerID: number) {
    this.router.navigate(["github_com_fullstack_lang_laundromat_go-" + "washer-display", washerID])
  }

  // set editor outlet
  setEditorRouterOutlet(washerID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_laundromat_go_editor: ["github_com_fullstack_lang_laundromat_go-" + "washer-detail", washerID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(washerID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_laundromat_go_presentation: ["github_com_fullstack_lang_laundromat_go-" + "washer-presentation", washerID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.washers.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.washers.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<WasherDB>()

      // reset all initial selection of washer that belong to washer
      this.initialSelection.forEach(
        washer => {
          washer[this.dialogData.ReversePointer].Int64 = 0
          washer[this.dialogData.ReversePointer].Valid = true
          toUpdate.add(washer)
        }
      )

      // from selection, set washer that belong to washer
      this.selection.selected.forEach(
        washer => {
          let ID = +this.dialogData.ID
          washer[this.dialogData.ReversePointer].Int64 = ID
          washer[this.dialogData.ReversePointer].Valid = true
          toUpdate.add(washer)
        }
      )

      // update all washer (only update selection & initial selection)
      toUpdate.forEach(
        washer => {
          this.washerService.updateWasher(washer)
            .subscribe(washer => {
              this.washerService.WasherServiceChanged.next("update")
            });
        }
      )
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s"]
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedWasher = new Set<number>()
      for (let washer of this.initialSelection) {
        if (this.selection.selected.includes(washer)) {
          // console.log("washer " + washer.Name + " is still selected")
        } else {
          console.log("washer " + washer.Name + " has been unselected")
          unselectedWasher.add(washer.ID)
          console.log("is unselected " + unselectedWasher.has(washer.ID))
        }
      }

      // delete the association instance
      if (sourceInstance[this.dialogData.SourceField]) {
        for (let associationInstance of sourceInstance[this.dialogData.SourceField]) {
          let washer = associationInstance[this.dialogData.IntermediateStructField]
          if (unselectedWasher.has(washer.ID)) {

            this.frontRepoService.deleteService( this.dialogData.IntermediateStruct, associationInstance )
          }
        }
      }

      // is the source array is emptyn create it
      if (sourceInstance[this.dialogData.SourceField] == undefined) {
        sourceInstance[this.dialogData.SourceField] = new Array<any>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField]) {
        this.selection.selected.forEach(
          washer => {
            if (!this.initialSelection.includes(washer)) {
              // console.log("washer " + washer.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + washer.Name,
              }

              associationInstance[this.dialogData.IntermediateStructField+"ID"] = new NullInt64
              associationInstance[this.dialogData.IntermediateStructField+"ID"].Int64 = washer.ID
              associationInstance[this.dialogData.IntermediateStructField+"ID"].Valid = true

              associationInstance[this.dialogData.SourceStruct + "_" + this.dialogData.SourceField + "DBID"] = new NullInt64
              associationInstance[this.dialogData.SourceStruct + "_" + this.dialogData.SourceField + "DBID"].Int64 = sourceInstance["ID"]
              associationInstance[this.dialogData.SourceStruct + "_" + this.dialogData.SourceField + "DBID"].Valid = true

              this.frontRepoService.postService( this.dialogData.IntermediateStruct, associationInstance )

            } else {
              // console.log("washer " + washer.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<WasherDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
