// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { SimulationDB } from '../simulation-db'
import { SimulationService } from '../simulation.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'

// generated table component
@Component({
  selector: 'app-simulationstable',
  templateUrl: './simulations-table.component.html',
  styleUrls: ['./simulations-table.component.css'],
})
export class SimulationsTableComponent implements OnInit {

  // used if the component is called as a selection component of Simulation instances
  selection: SelectionModel<SimulationDB>;
  initialSelection = new Array<SimulationDB>();

  // the data source for the table
  simulations: SimulationDB[];
  matTableDataSource: MatTableDataSource<SimulationDB>


  // front repo, that will be referenced by this.simulations
  frontRepo: FrontRepo

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort) sort: MatSort;
  @ViewChild(MatPaginator) paginator: MatPaginator;

  ngAfterViewInit() {

	// enable sorting on all fields (including pointers and reverse pointer)
	this.matTableDataSource.sortingDataAccessor = (simulationDB: SimulationDB, property: string) => {
		switch (property) {
				// insertion point for specific sorting accessor
  			case 'Machine':
				return (simulationDB.Machine ? simulationDB.Machine.Name : '');

  			case 'Washer':
				return (simulationDB.Washer ? simulationDB.Washer.Name : '');

				default:
					return SimulationDB[property];
		}
	}; 

	// enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
	this.matTableDataSource.filterPredicate = (simulationDB: SimulationDB, filter: string) => {

		// filtering is based on finding a lower case filter into a concatenated string
		// the simulationDB properties
		let mergedContent = ""

		// insertion point for merging of fields
		mergedContent += simulationDB.Name.toLowerCase()
		if (simulationDB.Machine) {
    		mergedContent += simulationDB.Machine.Name.toLowerCase()
		}
		if (simulationDB.Washer) {
    		mergedContent += simulationDB.Washer.Name.toLowerCase()
		}
		mergedContent += simulationDB.LastCommitNb.toString()

		let isSelected = mergedContent.includes(filter.toLowerCase())
		return isSelected
	};

    this.matTableDataSource.sort = this.sort;
    this.matTableDataSource.paginator = this.paginator;
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private simulationService: SimulationService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of simulation instances
    public dialogRef: MatDialogRef<SimulationsTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    // observable for changes in structs
    this.simulationService.SimulationServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getSimulations()
        }
      }
    )
    if (dialogData == undefined) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
        "Machine",
        "Washer",
        "LastCommitNb",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "Machine",
        "Washer",
        "LastCommitNb",
      ]
      this.selection = new SelectionModel<SimulationDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getSimulations()
    this.matTableDataSource = new MatTableDataSource(this.simulations)
  }

  getSimulations(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.simulations = this.frontRepo.Simulations_array;

        // insertion point for variables Recoveries

        // in case the component is called as a selection component
        if (this.dialogData != undefined) {
          this.simulations.forEach(
            simulation => {
              let ID = this.dialogData.ID
              let revPointer = simulation[this.dialogData.ReversePointer]
              if (revPointer.Int64 == ID) {
                this.initialSelection.push(simulation)
              }
            }
          )
          this.selection = new SelectionModel<SimulationDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.simulations
      }
    )
  }

  // newSimulation initiate a new simulation
  // create a new Simulation objet
  newSimulation() {
  }

  deleteSimulation(simulationID: number, simulation: SimulationDB) {
    // list of simulations is truncated of simulation before the delete
    this.simulations = this.simulations.filter(h => h !== simulation);

    this.simulationService.deleteSimulation(simulationID).subscribe(
      simulation => {
        this.simulationService.SimulationServiceChanged.next("delete")
      }
    );
  }

  editSimulation(simulationID: number, simulation: SimulationDB) {

  }

  // display simulation in router
  displaySimulationInRouter(simulationID: number) {
    this.router.navigate(["github_com_fullstack_lang_laundromat_go-" + "simulation-display", simulationID])
  }

  // set editor outlet
  setEditorRouterOutlet(simulationID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_laundromat_go_editor: ["github_com_fullstack_lang_laundromat_go-" + "simulation-detail", simulationID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(simulationID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_laundromat_go_presentation: ["github_com_fullstack_lang_laundromat_go-" + "simulation-presentation", simulationID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.simulations.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.simulations.forEach(row => this.selection.select(row));
  }

  save() {

    let toUpdate = new Set<SimulationDB>()

    // reset all initial selection of simulation that belong to simulation through Anarrayofb
    this.initialSelection.forEach(
      simulation => {
        simulation[this.dialogData.ReversePointer].Int64 = 0
        simulation[this.dialogData.ReversePointer].Valid = true
        toUpdate.add(simulation)
      }
    )

    // from selection, set simulation that belong to simulation through Anarrayofb
    this.selection.selected.forEach(
      simulation => {
        let ID = +this.dialogData.ID
        simulation[this.dialogData.ReversePointer].Int64 = ID
        simulation[this.dialogData.ReversePointer].Valid = true
        toUpdate.add(simulation)
      }
    )

    // update all simulation (only update selection & initial selection)
    toUpdate.forEach(
      simulation => {
        this.simulationService.updateSimulation(simulation)
          .subscribe(simulation => {
            this.simulationService.SimulationServiceChanged.next("update")
          });
      }
    )
    this.dialogRef.close('Pizza!');
  }
}
