// generated by gong
import { Component, OnInit, Inject, Optional } from '@angular/core';
import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop';

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

import { Router, RouterState } from '@angular/router';
import { SimulationDB } from '../simulation-db'
import { SimulationService } from '../simulation.service'

import { FrontRepoService, FrontRepo, NullInt64 } from '../front-repo.service'
@Component({
  selector: 'lib-simulation-sorting',
  templateUrl: './simulation-sorting.component.html',
  styleUrls: ['./simulation-sorting.component.css']
})
export class SimulationSortingComponent implements OnInit {

  frontRepo: FrontRepo

  // array of Simulation instances that are in the association
  associatedSimulations = new Array<SimulationDB>();

  constructor(
    private simulationService: SimulationService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of simulation instances
    public dialogRef: MatDialogRef<SimulationSortingComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };
  }

  ngOnInit(): void {
    this.getSimulations()
  }

  getSimulations(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        let index = 0
        for (let simulation of this.frontRepo.Simulations_array) {
          let ID = this.dialogData.ID
          let revPointerID = simulation[this.dialogData.ReversePointer]
          let revPointerID_Index = simulation[this.dialogData.ReversePointer+"_Index"]
          if (revPointerID.Int64 == ID) {
            if (revPointerID_Index == undefined) {
              revPointerID_Index = new NullInt64
              revPointerID_Index.Valid = true
              revPointerID_Index.Int64 = index++
            }
            this.associatedSimulations.push(simulation)
          }
        }

        // sort associated simulation according to order
        this.associatedSimulations.sort((t1, t2) => {
          let t1_revPointerID_Index = t1[this.dialogData.ReversePointer+"_Index"]
          let t2_revPointerID_Index = t2[this.dialogData.ReversePointer+"_Index"]
          if (t1_revPointerID_Index && t2_revPointerID_Index) {
            if (t1_revPointerID_Index.Int64 > t2_revPointerID_Index.Int64) {
              return 1;
            }
            if (t1_revPointerID_Index.Int64 < t2_revPointerID_Index.Int64) {
              return -1;
            }  
          }
          return 0;
        });
      }
    )
  }

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.associatedSimulations, event.previousIndex, event.currentIndex);

    // set the order of Simulation instances
    let index = 0
    
    for (let simulation of this.associatedSimulations) {
      let revPointerID_Index = simulation[this.dialogData.ReversePointer+"_Index"]
      revPointerID_Index.Valid = true
      revPointerID_Index.Int64 = index++
    }
  }

  save() {

    this.associatedSimulations.forEach(
      simulation => {
        this.simulationService.updateSimulation(simulation)
          .subscribe(simulation => {
            this.simulationService.SimulationServiceChanged.next("update")
          });
      }
    )

    this.dialogRef.close('Sorting of '+ this.dialogData.ReversePointer+' done');
  }
}
